= Thinking tools

== Math

=== Bayes' Theorem

Posterior = Likelihood * Prior

p(H|D) = p(D|H) * p(H) / p(D|not H)

The probability of a theory is the previous probability times the likelihhod of observing data if it is True, divided by the probability of observing it if it is not true.

=== Symmetry

Some system exhibi symmetry, which can be used to model them.

e.g. Newtonian Forces

=== Conserved Quantity

Often times a system conserves a an (abstract) quantity.

e.g. Kinetik Energy is converted to potential if an object is pulled up in a gravitational field

=== Analysis

Certain functions allow the calculation of the gradient: local information of the curvature. 

Intuitive: How much and in what direction changes the output if the input changes a little.

==== Integration
Generalization of sum to non-discrete functions.

see Discrete vs Non-discrete


=== Discrete vs. Non-discrete

* Discrete: System consists of some quantity which cannot be divided further, e.g. elementary particles and integers#
* Non-discrete: Values infinitely dividible, e.g. real numbers 

=== Linear Systems vs Nonlinear

* Linear:
** Combination of linear systems yield a linear system
** slight changes in input lead to slight changes in output
** can be easily modeled
* Nonlinear:
**  Cannot be easily combined
** output may change radically if input changes
** difficult to model
-> Chaotic systems

=== Deterministic vs Non-deterministic
* Deterministic : Output always the same
* Non-deterministic: Ouput not always the same, randomness

=== Chaotic system
 
Slight changes in input conditions lead to unpredictiable behaviour even if function of system is perfectly known and System is deterministic.

see Deterministic

see Linear Systems


=== Local vs Global Optimum

* Local optimum: Equlibrium state of system which cannot be improved by small steps. Usually attractor states and equlibrium. Needs energy to escape. E.g. some chemical reations need initial heat to get started
* Global optimum: Best possible value, cannot be improved in any way.

see Attractor states
see Equilibrium


=== Differential Equations
 
Rate of change is a function of the current state of the system.

d(f(x)) = g(f(x)) 

see Analysis

=== Phase space

Coordinate space can be not only time and position but more abstract, e.g X=Number of rabbits, Y=Number of foxes, Curve in this space models yearly change of populations.

==== Attractor states

Points in phase space which the system is pulled towards.

see Differential Equations

see Analysis

=== Phase transition
System goes from one set of states with internal dynamics into another one which is qualitatively different.
* e.g. Water(fluid, can dissolve things) -> Ice (hard, cannot, lower density)
* e.g. agricultural -> industrial society


=== Approximations

Not computing the actual value but some value close to it, which is easier to compute.
*Bad: Estimate diverges from real value
*Good: Estimate converges to value, e.g. n-sided polygon converges to circle if n goes to infinity

=== Invertability

Not all functions have a counterpart which returns the original input,e.g. f(x) = 0 * x   -> Some functions lose information 


=== Probability distribution

Function that tells, how likely it is to observe some value.

Most important:

* Normal/Gaussian: Bell curve. Appears if many, small, uncorrellated effects add up.
** Student's t, Fait tail distribution: Adding up multiple normal. Rare events become way more likely. See Black Swan event.
Power law/Pareto distribution: Very small/ likelyhood for one end of values, very high likelyhood for other and of values. Generated by multiple, dependent effects
** see Pareto distribution
** see Positive feedback loop

* Binomial: Coin flip


See Bayes' Theorem

=== Closed form solution

Solution to a problem which can be computed in constant time, usually without computing intermediate solutions.

E.g. Fibonacci: 1,1,2,3,5,...
Computing nth fibonacci number.
Naive approach: Computing fib(0),fib(1)
But formula for nth number exists°

=== Divide & Conquer

Solving a problem by dividing the problem and adding the solutions of the subproblems.

See Parallelization


== Computer Science

=== Algorithmic complexity

Measure of how much resources (mostly time and memory) a computation consumes depending on the input length.

O(1): Finding and object in a hash map(dict)
O(n): Going through a list, e.g. finding maximum 
O(n^2): List of lists, e.g. naive sorting
O(e^n):  All possible combinations of elements in a set, e.g. travelling salesman problem

see Linear vs. Non-linear

=== Gödel Number

Every computation can be mapped to an integer > Every object can have a unique identifier


=== Turing Machine

Universal model of computation, can be used to study types of computation.

=== Diagonalisation proof

There exists no program which can compute the result of all programs without running it.
-> There exists computation which cannot be short circuted and need to be run to see the result


=== Hashing

Easy to compute function which returns almost always a unique value for an object. Cannot be easily reversed. Can be used as a secure key.

* see Gödel Number
* see Block Chain
* see Invertability

=== Block Chain

Chain of hashing blocks. Allows distributed validation of computation by burning energy to find the reverse hash of some computation + previous hash.

* see Hashing
* see Distributed computing

=== Parallelization, Distributed computing, Scalability
 
Increasing speed of execution by splitting of the task and giving it to multiple workers.

==== Amdahl's Law

Given the fraction of the taks which can be parallelized, computes how much speedup is gained with n workers.

=== Brute Force Algorithm

Just trying all possibile combinations, e.g. opening a number lock.

see Algorithmic Complexity

=== Recursion

Function calling itself with different arguments.

=== Abstraction

Higher level interface, which pretends to be atomar, but is actually built by hidden components. E.g. operating system pretends that there are files, devices etc. when in reality there are only electrons moving in semiconductors. Not limited to CS though: E.g. a  lock builds a security device from mechanical contraptions.

==== Leaky Abstraction

Abstraction that leaks the lower level into higher, usually resulting in unexpectd behaviour, bugs. Can only be understood by the underlying parts.

* see Hacking

=== Hacking

Exploiting the underlying structure of an abstraction.

* e.g. abusing stack overflows
* e.g. lock picking

=== Neural Networks

General function approximators, constructed by stacking building pieces. Can be trained by going into direction of gradient with respect to loss.

* see Analysis
* see Approximation

== Biology

=== Evolution

Copy + Variation leads to an optimization of the copied object with respect to some measure. -> Every environment selects for some trait.

see Meme

=== Niche partitioning

Organisms will evolve the usage of different resources to avoid competition,e.g. Darwin's Finks and specialization of labor

=== Ecosystem

System of co-evolved organisms, filling different niches.

=== Convergent evolution

Same species evolve same traits if faced with the same problems.
e.g. Fish, Dolphin, Ichtyosaurs


=== Gradients lead to diversity


Gradients, e.g. amount of light in forest, salinity at beach leads
to different species occupying each niche.
Also in cultural context, e.g. language barrier lead to different types of cultures.

see Niche Partitioning

==== Diversity is proportional to log(area)

E.g. number of species in area of size  2 = log(2) * number of species in are of size 1
Why tho?

=== Sexual Selection

In sexually reproducing species a signal of good genes can be become it's own thing, even lowering the overall fitness.
* e.g. peacock's tail
* e.g. Human dance and music

* see Mating Mind Hypothesis
* see Signalling

=== Mating Mind Hypothesis

Human mind evolved primarly as a display for sexual selection and not as a rational, problem solving tool


=== Extended phenotype

Phenotype is not only direct physical traits, but also artifacts created by animal. E.g. Bee's hive, beaver's damn. Thus gene indirectly code for those too.

See Biological Evolution

=== Gene-culture co-evolution

Human cultures and genes co-evolve. E.g. cow herding practises lead to a mutation which allows adults to digest milk.

See Evolution


=== Carrying capacity

Population number a given are can sustain. 

* e.g. number of wolves that can exist while having a stable sheep populatoion
* Also in other areas: e.g. number of profitable ice creams shops in a city 

== Cybernetics & Game theory

=== Zero-sum & Positive-sum & Negative-sum Games

* Zero-sum: Ressource cannot be generated and agents fight for piece.
* Positive-sum: Games allows creating, cooperation can lead to both parties be better off, e.g. trade
* Negative-sum: Playing the game leads to be both parties be worse of, e.g. WWI


see Prisoners' Dilemma

=== Nash equilibrium

Set of strategies which are optimal in a sense that it is the best option given the others players strategies.


=== Schelling Point

Point where agents meet in absense of communication. E.g if you had to meet somebody without beeing able to talk, both parties would likely choose something like central station, 12 o' clock.

=== Pareto optimal

Strategy or allocation of ressources which cannot be improved in one dimension without beeing worse in some other dimension.


=== Prisoners' Dilemma

Game where cooperation-cooperation is worse then one party defection = cooperation-defect, but both parties defecting = defect-defect is even worse.

=== Information assymetry

One agent has more information then other which can not be easily transferred. E.g. even a realtively new, but used car is worth way less, because the buyer does not know if the car has a problem and the seller will likely not tell.

* see Market
* see Signalling

=== Moloch, Inadequate Equlibria

Bad local minimum/Nash equlibrium in system. System is disfunctional, but every single actor would experiece negative 
consequences ofif trying to change it. E.g. Academia: Overall publish-or-parish bad, but no single scientist has incentive to not publish in high ranking journal.


* see Local minimum
* see Nash equlibrium
* see Equlibrium

=== Path dependency

Current system might be sub-optimal, but cannot be easily changed because of previous decisions. Legacy systems also often need to be maintained.

* e.g. Blind spot in human eyes exists because of  path mammalian eye evultion tool. Squids dont have it.

See Moloch

=== Positive & Negativ feedback loop

* Positive: Initial force is amplified
** Inital spark leads to fire which leads to more fire 
* Negative: Intial force is dampened
** Bimetal regulation for constant heat: When bimetal becomes to hot it flexes, disabling the fuel valve, which in turn lowers temperature.



=== Winner takes it all

In some games, being the second or third one is insufficient, as only the first one reaps benifits

* e.g. Zero-sum games between competing firms, when the potential market is small
* e.g. Reproduction in gorillas: Only alpha male reproduces

* see Matthew effect
* see Network effect
* see Zero-sum games

=== Network effect

Value of a network is proportional to the number of connections, not nodes: Exponential vs linear. Thus only a small difference in initial size can lead to a different outcome, as new members join the network that has the highest value, thus increasing the netwok's value even more.

* see Linear vs. Non-linear
* see Winner takes it all
* see Positive feedback loop.


=== Agressive vs Defensive play

Most of the time an agressive strategy is better then a defensive one: The aggressor can usually attack multiple times, while the defender needs only one misstep to be eliminated.

=== Tit-for-Tat
Strategy where initially one cooperates, but defects, once the other player starts defecting. Can be played with forgiveness, that after n rounds, one start cooperating again.

* see Prisoners' Dilemma
* see Nash equlibrium


== Economics


=== Supply & Demand

In an efficient market, the prices are determined by supply and demand. If more people want the same good, prices increase, which leads to more people producing the good, which brings prices down again.

* see Negative feedback loop
* see Market
* see Efficient Market Hypothesis

=== Reveled Preferences

Idea that one should look more at what people do and spend money one, instead of listening to what the say, if one wants to figure out, what the real intentions are.

* see Subconcious
* see Tribalism



=== First mover advantage

Advantage company has be moving in the market first. Mostly based on network effect and stickiness of choices.

* see Network effect

=== Pareto distribution

Tendecy for a minorities of things to have a majority of effect.

* e.g. 20 % of households hold 80 % of wealth
* minority of authors sell majority of books
* optimizing the first few lines of code usually leads to the biggest increase

see Probability distribution

=== Mathew Effect

Winners are rewarded with easier wins in the future. E.g. famous author is going to sell more books because they are already famous, which makes them even more famours.

See Pareto distribution
See Positive feedback loop



=== Trade-off

Every choice has pro and cons, which need to me measured against each other.


=== Opportunity cost

Realization that every choice has the minimum trade-off of what you could have done otherwise, e.g. work or spend leisure time.

see Trade-off

=== A??? theorem

Even if one party is more productive in all aspects, if there is at least a difference in relative productivity, both parties can be better of if they trade.

=== Minium Viable Product

Minimum set of features a product needs to be useful to customer and sellable.


=== Marginal value and cost


* Marginal value: Value the n+1 th thing gives, after already having n things,
**  e.g. 2nd pizza has less value if you have already eaten one.
** e.g. hiring a 10 th farm worker will give less value then hiting the first 
* Marginal cost: Cost of producing the n+1 th thing after having already produced n.
** e.g. If machine is already payed, producing more things is way cheaper then producing the first.

see Economy of scale


=== Monopoly

Having the lone possibility of selling a service or product.

* Natual monopoly: Beeing the only one who has skills to do it.
* Unnatural: e.g. Patents


=== Market

Markets usually produce optimal outcomes if externalities are priced in and there is information assymetry.

see Externalities
see Information Assymetry

=== Externalitites

Side effects of product/service which are usually not captured by the acutal price

* Negative: e.g. CO2 when no carbon tax
* Positive: e.g. Education

=== Efficient Market Hypothesis

If market has no information assymetry, it is hard to outcompete the aggregate information, e.g. stock market. 

=== Economies of scale

Producing more of a product lowers marginal cost up to certain point. Depends heavily on algorithmic complexity and parallelizability.

* see Marginal Value & Cost
* see Algorithmic complexity
* see Parallelization


=== Option

Gurantee to sell/buy a certain product at certain time at a certain price. Can be used as insurance.


=== Hedging

Allocating ressources as to minimize risk.

See Option

=== Skin in the game

When people are invested in a prediction, monetarly or otherwise, their predictions will be more realistic and less grown to group think.

=== Tragedy of the commons


Unclear ownership of shared resources can lead to overexploitation, e.g. fishing until all fish are caught

* see Diffusion of responsibility
* see Postive feedback loop

=== Bubble

Positive feeeback loops that leads to an inflation of the price of some asset (e.g. Tulips, Houses) which at some point crashes

* see Madness of Crowds
* see Postive feedback cycle

=== Economic cycle

Observations that economies expand and contract in multi-year long cycles.
Why tho?


=== Class

Idea that different types of social groups, which different goals, practises, knowledge etc exist. Most of time comes with conflict.






== Physics 

=== Newtonion Physics


Basic laws of movements.


F = M*a

Force is mass times acceleration



=== Boyle-Marriote


P = V*T

Pressure is proportional to Volume times Temperature.

-> Gases that expand cool.

-> Increasing temperatur of a closed system increases the pressure.

=== Equilibrium

State of system in which forces that influence system are in balance and no change happens.

* Stable: In local minium
* Unstable: Not in local minimum

See local minium


=== Relativity

At high energies and masses time is influenced and not independent of space. Speed influences mass.

E = m*c²
Energy is equal to mass times speed of light sqaured




== Decision theory, Argumentation & Modelling


=== Map vs.Territory

You can never experience the world directly only through your mental model. You must no confuse this!


=== Epistemic Standard

Level of proof one needs to accept a hypothesis. Some people need more, some less. Usually one can dismiss theories more easilty by people with abysmal epistemic standard. (Crackpot theories)

See Bayes theorem

=== Epistemic Distance

Number of other, more basic theories one needs to accept to be able to discuss the theory in question. E.g. to accept evolution one first needs to accept that the Bible was not written by God etc.


=== Difference in feedback quality ( Needs a good name)

Different fields exhibit different quality, and thus the average level of expertise quite varies. To have good feedback quality, a field must fufill different criteria:

* Speed of feedback: If feedback is slow, it is hard to learn and iterate.
* Open: Can anybody go into the field and make predictions or is there an unmeritocratic extry hurdle?
* Deterministic: If the result is heavily influenced by random events, it is hard to draw conclusion.
* Observable: Is the result of actions observable.
* Skin in the game: Are the agents subject to money or status prices? see Skin in the Game
* Group bias: Are the agents part of a single ideological group? See Tribalism

* Fields with good feedback cycles:
** Programming
** Sports
* Fields with worse ones:
** Academic Sociology
** Politics


=== Inside vs. Outside view

Know areas and topics are usually seen as more diverse and lively than unknown topics.


=== Unfair demands of purity

Demanding that the other party's proposal/argument fulfills (unrealisitic) criteria, while one's own does not.

=== Recognise Confusion

Realize when you are confused. This means your model broke down and it's time to investigate why.

See Bayes' Theorem

=== Eulern

Bullshitting someone with unrelated data and equations to derail the conversation.


=== What-about-ism

Derailing the conversation by asking "but what about UNRELATED topic"


=== Straw-Manning vs Steel-Manning

* Straw-Manning: Disproving the other side, by attacking not the real argument but a weak/distorted version
* Steel-Manning: Trying to disprove the strongest version of the the other side's argument

=== Truism

Piece of knowledge with is widle known to be true, but might not be and is not usually questioned.

=== Fox vs Hedgehog

The hedgehog knows one big thing (one idealogy/lens), the fox knows many things.

=== Intuition pumps
When performing some (ethics) thought eperiments, change some part, which should not change the outcome. If it does, why so?


E.g. In trolley problem, feels pushing the person on the rails same os letting them fall?

=== Anthropic principle

What does your existence as an observer say about your universe?
-> since you exit your universe must support the existence of observers like you.
What does you universe say about you as the average observer?
-> If you would not know anything about you, but you were at a dentist's conferenece, there is a high likelihood you are also a dentist.

=== Chesterton's Fence

Old cultural practises might seem harsh, e.g. taboo against pre-marital sex. But before you abolishing them you should consider why there were there at the first place, in this case minimizing single mothers.

==== Chesterton's Meta-Fence

In the last couple of hundered years, on average, abolishing must harsh cultural practises had a net positive effect.

* see Cultural Evolution

=== Survivor Bias

Only things that survive can be observed, giving a skewed version of the real distribution.  E.g. WW2 planes had no holes in certain parts, because the ones that were hit there, did not return.


==== History is written by the winners

Surviving documents are biased towards the side who wrote them, which is more likely the one that won in conflicts.

* see Map vs. Territory

== Psychology

=== What basic human cognitive capacities are you missing?

Apparently some people have no inner dialog, are missing the ability to visualize things. One should not generalize from ones own mental processes to other's.

See Map vs Territory
See Theory of Mind


=== System 1 vs System 2 thinking

* System 1: Fast, intuitive, inprecise, biased
* System 2: Slow, deliberate, trained, cognitive exhausting


see Cognitive bias


=== Cognitive bias

Human brains are not perfect bayesian machines, but evolved shortcuts and makes underlying assumptions.

** Recency bias: Recent information is more heavily weighed
** Availability bias: More easily recalled information is more heavily weighed
** Halo-effect: Being good in one dimension leads other to beleave you are good at other things,
** Priming: Initial values as sticky, even if disproven. see Bayes' Theorem
** Status-quo bias: Current status is favored, even if suboptimal
** Natural bias: Thing is good, because it's natural
** Agency bias: Tendency to attrbute agency to non-living processes and overestimate ageny of non-human agents.
** Story bias: Tendency to believe a thing if it is wrapped in a plausible story
** Lay physics: Intuitive understanding of Newtonion physics, but is often wrong, e.g. inertia
see Newtonian physics 
** Inside vs Outside bias: See Inside vs. Outside view

TODO: More biases


=== Theory of mind

Ability to model mental processes of other agents, mainly other humans.

see Agency bias


=== Subconcious

Not all human though processes are accesible by the concious mind. Often decision are made without knowledge of why. Afterwards plausible story is created to justify it.

see Story Telling

=== Story telling

Human minds understand a story with agent's that have goals and clear groups most easily. Things that are not easily brought into this form, e.g. high-dimensional, non-deterministic, chaotic processes are difficult to understand.


* see Deterministic vs. non-deterministic
* see Chaotic system
* see Theory of mind


== Sociology & Organization


=== Meme

Ideas underly similar mechanisms as genes: They mutate, they are propagated, they provide advantages/disadvantages to carrier. Thus we would expect, e.g. memes to evolve to be more easily transmitted.


* see Story telling
* see biological evolution

=== Cultural Evolution

Idea that cultural practises, similar to species, evolve to maximise the survival of group. 


* see Meme
* see Chesterton's Fence

=== Wisdom of crowds

Aggregating estimates of multiple people can yield a better result.

See Madness of crowds
See Efficient Market Hypothesis


=== Madness of crowds

Tendency of people to lose identity in mobs, which leads to actions a single person would never do.

* see Holiness Spiral
* see Diffusion of responsibility
* see Tribalism

=== Diffusion of resposibility

If multiple people share resource/decision, nodoy feels respobisbile.
See Tragedy of the commons

== Dunbar's Number

Humans evolved in small groups in the 10^2 s. Thus it is very difficult to have personal relationships with more than ~150 people.

=== Singalling

Behaviour or trait which signals an underlying, but not easily demonstratable trait. To be good a signal, it must be:
* Costly
* Less costly for an agent that has the underlying trait

* e.g. Peacock's tails signals strenght because only strong males can accept negative consequences of it.
* e.g. University degree signals intelligence and grit. It's is costly in time and money, bonesut easier for smart and diligent people.
* e.g. religious practisis like circumcision singal commitment to group. Easier to accept mutiliation if you are a true believer.

* see Sexual selection
* see Information Assymmetry
* see Point deer - make horse

=== Status

After basic needs are met, humans compete (subconciously?) mostly for status, which has it's origins likely in mate selection, but became it's own thing. Imaginary fame points. Leads many people into career's which increase fame like musicians and politics.


see Sexual Selection


=== Virtue signalling

Mostly derogative. Tendency to signal owns virtue to increase status without paying price, e.g. rainbow profile pics. Slacktivism.

=== Holyness Spiral

Process where signalling one's own virtues leads to a positive feedback loop of ever increasing real signals with higher cost. Can lead to complete extinction of run to long. e.g. Communist Cambodia

* see Status
* see Virtue Signalling


=== In-group vs Out-group, Tribalism, Group think

People are very tribal, because that's the environment the human mind evolved. Believes and rituals are a strong marker of beeing part of a group and people really want to belong. This leads to arguments beeing soldiers and core beliefs of the group are not questioned.  In-group is usually seen as better, having higher ethics and beeing more diverse than Out-group. Also the In-group is very heavily defended, especially against outside criticism. Politics is the mind killer.

* see Inside vs. Outside view
* see Unfair demand for purity

=== Point deer - make horse
Chinese minister plans coup. Shows others a deer and tells them it's a horse. Ones who see the plan say it's a horse, ones who disagree are executed: Ridiculus belivies are a strong marker of group membership. Everybody can believe the truth, only a true believer can believe nonsense.

* see In-group vs Out-group

=== Sour grapes
Fox cannot reach the grapes, claims he did not want them anyways:
Tendency to downplay value of things which could not be obtained.

=== Bio-Leninism

Tendency for organisation to select from unqualified people for their personnel, as those will be loyal, because they have no other option.

=== Culture matters

Culture context matters,e.g. hot air ballon and bycicle where invented in the 1800's, but actually no to little scientific discovieries had to be made. It was likely because of a change in mindset that things could be discovered.

=== Subculture

Group of people that diverges from the mainstream culture to construct their own Status hierachy, usually with different ideas, cultural practises and looks.

* e.g. Punks
* e.g. Academia


* see Tribalism
* see Status